xcopy /y  D:\project\wux2\wux\checkbox-group D:\project\wux2\src\wux\checkbox-group 
xcopy /y  D:\project\wux2\wux\checkbox D:\project\wux2\src\wux\checkbox 
xcopy /y  D:\project\wux2\wux\icon D:\project\wux2\src\wux\icon 
xcopy /y  D:\project\wux2\wux\cell-group D:\project\wux2\src\wux\cell-group 
xcopy /y  D:\project\wux2\wux\cell D:\project\wux2\src\wux\cell 
xcopy /y  D:\project\wux2\wux\button D:\project\wux2\src\wux\button 
xcopy /y  D:\project\wux2\wux\tag D:\project\wux2\src\wux\tag 
xcopy /y  D:\project\wux2\wux\input D:\project\wux2\src\wux\input 
xcopy /y  D:\project\wux2\wux\accordion-group D:\project\wux2\src\wux\accordion-group 
xcopy /y  D:\project\wux2\wux\accordion D:\project\wux2\src\wux\accordion 
xcopy /y  D:\project\wux2\wux\grids D:\project\wux2\src\wux\grids 
xcopy /y  D:\project\wux2\wux\grid D:\project\wux2\src\wux\grid 
xcopy /y  D:\project\wux2\wux\media D:\project\wux2\src\wux\media 
xcopy /y  D:\project\wux2\wux\select D:\project\wux2\src\wux\select 
xcopy /y  D:\project\wux2\wux\tabs D:\project\wux2\src\wux\tabs 
xcopy /y  D:\project\wux2\wux\tab D:\project\wux2\src\wux\tab 
xcopy /y  D:\project\wux2\wux\badge D:\project\wux2\src\wux\badge 
xcopy /y  D:\project\wux2\wux\floating-button D:\project\wux2\src\wux\floating-button 
xcopy /y  D:\project\wux2\wux\popup D:\project\wux2\src\wux\popup 
xcopy /y  D:\project\wux2\wux\card D:\project\wux2\src\wux\card 
xcopy /y  D:\project\wux2\wux\filterbar D:\project\wux2\src\wux\filterbar 
xcopy /y  D:\project\wux2\wux\search-bar D:\project\wux2\src\wux\search-bar 
xcopy /y  D:\project\wux2\wux\popover D:\project\wux2\src\wux\popover 
xcopy /y  D:\project\wux2\wux\selectable D:\project\wux2\src\wux\selectable 
xcopy /y  D:\project\wux2\wux\radio D:\project\wux2\src\wux\radio 
xcopy /y  D:\project\wux2\wux\radio-group D:\project\wux2\src\wux\radio-group 
xcopy /y  D:\project\wux2\wux\animation-group D:\project\wux2\src\wux\animation-group 
xcopy /y  D:\project\wux2\wux\backdrop D:\project\wux2\src\wux\backdrop 
xcopy /y  D:\project\wux2\wux\countdown D:\project\wux2\src\wux\countdown 
xcopy /y  D:\project\wux2\wux\countup D:\project\wux2\src\wux\countup 
